### ISSUE TITLE
Site design

### ISSUE THREAD

**Issue by kulga** [Ledstrain/ledstrain.github.io#1]
My thinking is the below structure:
Plus any other root directories (like related to activism?)

```
./
└── Devices
    └── Category
        └── Subcategory
            ├── Device_1
            ├── Device_2
            └── Device_3
```

I'm angling for as much automation as possible, so that Device(s) in Subcategory are autogenerated into a list in Subcategory and the same for Category and Devices. It should make up at least a portion of it.
[This may be relevant](https://stackoverflow.com/questions/17118551/generating-a-list-of-pages-not-posts-in-a-given-category#17913214) (reference)

**Comment by jtl999** [comment]
I like this directory structure. Would we have a template for each device page?

**Comment by kulga** [comment]
Templates like [this](https://jekyllrb.com/docs/templates/)? Not sure I follow.
Maybe we're thinking the same thing:

My thinking is have a custom layout for device pages (what you mean by template?).
Then a default order (template?) of device name, model, attributes / tags / categories, description, comments(?) and such.

**Comment by jtl999** [comment]
That's what I was thinking, thanks.

**Comment by jtl999** [comment]
Never really used Jekyll, but most static site generators are similar.

**Comment by jtl999** [comment]
lol

Tonight because I was bored I cloned the master repository and started making changes but then I realized you had the `beta` branch. 

Will check it out

Doh.

**Comment by jtl999** [comment]
Problem.

When I build the site from the beta page the directory in `_site` containing posts of type `device` is named `d`.

```
total 32
drwxr-xr-x  12 jtl  staff   408B 29 Jun 21:14 .
drwxr-xr-x  20 jtl  staff   680B 29 Jun 21:14 ..
-rw-r--r--   1 jtl  staff    18B 29 Jun 20:04 CNAME
-rw-r--r--   1 jtl  staff   1.0K 29 Jun 20:04 LICENSE
drwxr-xr-x   3 jtl  staff   102B 29 Jun 21:14 about
drwxr-xr-x   4 jtl  staff   136B 29 Jun 21:14 assets
drwxr-xr-x   3 jtl  staff   102B 29 Jun 21:14 css
drwxr-xr-x   9 jtl  staff   306B 29 Jun 21:14 d
-rw-r--r--   1 jtl  staff   3.1K 29 Jun 21:14 feed.xml
-rw-r--r--   1 jtl  staff   2.2K 29 Jun 21:14 index.html
drwxr-xr-x   4 jtl  staff   136B 29 Jun 21:14 js
drwxr-xr-x   3 jtl  staff   102B 29 Jun 21:14 welcome-to-jekyll
```

**Comment by kulga** [comment]
> posts of type device is named d.

No kidding


```
#_config.yaml
defaults:                                                                       
    scope:                                                                      
        path: "_devices" # an empty string here means all files in the project  
        type: "devices"                                                         
    values:                                                                     
        layout: "devices"                                                       
                                                                                
collections:                                                                    
    devices:                                                                    
        output: true                                                            
        permalink: /d/:path/:slug
```

Having devices as their own special collection I believe will allow for unique layouts for them as opposed to jamming it into posts / pages (which can have their own layout this way)
